#!/usr/bin/env python3
import requests
import argparse
from concurrent.futures import ThreadPoolExecutor

# GETTING ARGUMENT FOR DOMAIN NAME
parse = argparse.ArgumentParser()
parse.add_argument("-d", "--domain", required=True, help="target domain")
args = parse.parse_args()

# CREATE A REQUIRED VARIABLILES 
protocol = 'https'
port = 443
threads = 10
wordlist = '/usr/share/dnsrecon/dnsrecon/data/subdomains-top1mil-20000.txt'

# PRINT THE TARGET
target = f"{protocol}://{args.domain}:{port}/"
print(target)

# USE MULTI THREADING TO SEND REQUESTS TO GET THE SUBDOMAIN
def subdomain(word):
        word = word.strip()
        fullurl =f"{protocol}://{word}.{args.domain}:{port}/"
        try:
                response = requests.get(fullurl, timeout=10)
                size = len(response.content) 
                if response.status_code == 200:
                        print('\033[92m' + '[ ' + fullurl + ' , ' + str(response.status_code) + ' ]')
                elif 300 <=response.status_code <= 399:
                        print('\033[93m' + '[ ' + fullurl + ' , ' + str(response.status_code) + ' ]')
                elif 400 <=response.status_code <= 499:
                        print('\033[91m' + '[ ' + fullurl + ' , ' + str(response.status_code) + ' ]')
                elif 500 <=response.status_code:
                        print('\033[91m' + '[ ' + fullurl + ' , ' + str(response.status_code) + ' ]')
                else:
                        print(response.status_code)
        except requests.exceptions.RequestException:
                pass

with open(wordlist, "r") as f:
    with ThreadPoolExecutor(max_workers=threads) as executor:
        executor.map(subdomain, f)
